name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
  deploy-on-failure:
    runs-on: ubuntu-latest
    needs: cypress-run
    if: failure()
    steps:
      - name: Log Failure
        run: echo "Test job failed. Executing failure handling tasks."